<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>som</string>
	</array>
	<key>name</key>
	<string>SOM-Smalltalk</string>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>comment.smalltalk</string>
		</dict>
		<key>constant</key>
		<dict>
			<key>match</key>
			<string>\b(nil|true|false|primitive|system)\b</string>
			<key>name</key>
			<string>constant.language.smalltalk</string>
		</dict>
		<key>reserved_variable</key>
		<dict>
			<key>match</key>
			<string>\b(self|super)\b</string>
			<key>name</key>
			<string>variable.language.smalltalk</string>
		</dict>
		<key>string</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.smalltalk</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.SOM-smalltalk</string>
	<key>uuid</key>
	<string>2fb9a222-0a36-4f7d-a3a4-58c523cd7437</string>
</dict>
</plist>
