<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>som</string>
	</array>
	<key>name</key>
	<string>SOMns</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#module</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>accessModifier</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.modifier.som</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(public|private|protected)\b</string>
		</dict>
		<key>assignmentOperator</key>
		<dict>
			<key>match</key>
			<string>(?&lt;!:):=</string>
			<key>name</key>
			<string>keyword.operator.assignment.som</string>
		</dict>
		<key>binaryMsgPattern</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#binarySelector</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#slotDecl</string>
				</dict>
			</array>
		</dict>
		<key>binarySelector</key>
		<dict>
			<key>match</key>
			<string>[+/\\*~&lt;&gt;=@%|&amp;?!,-]+</string>
			<key>name</key>
			<string>keyword.operator.binary.som</string>
		</dict>
		<key>blockExp</key>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.block.begin.som</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.block.end.som</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#exps</string>
				</dict>
			</array>
		</dict>
		<key>classDefBlock</key>
		<dict>
			<key>begin</key>
			<string>\((?=[^*])</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.block.begin.som</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.block.end.som</string>
				</dict>
			</dict>
			<key>name</key>
			<string>class-definition-block</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#accessModifier</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywordSegment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#multilinecomment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#classHeader</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#classDefBlock</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#slotDecls</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#classDecl</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#category</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#methodDecl</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#classSideColon</string>
				</dict>
			</array>
		</dict>
		<key>classHeader</key>
		<dict>
			<key>begin</key>
			<string>(?=(?:\w+\s+)?(?:class)\s+\w+\s*)</string>
			<key>end</key>
			<string>(?=\()</string>
			<key>name</key>
			<string>meta.class.som</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#accessModifier</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywordSegment</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.class.som</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.class.som</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(class)\s+(\w+)</string>
					<key>name</key>
					<string>meta.class.identifier.som</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>=</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.extends.som</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\()</string>
					<key>name</key>
					<string>meta.definition.class.inherited.classes.som</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\b(\w+(?::)?)</string>
							<key>name</key>
							<string>entity.name.function.som</string>
						</dict>
						<dict>
							<key>match</key>
							<string>&lt;:</string>
							<key>name</key>
							<string>storage.modifier.mixin.som</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>classSideColon</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.class-side.som</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;=\))\s*(:)\s*(?=\()</string>
		</dict>
		<key>constants</key>
		<dict>
			<key>match</key>
			<string>\b(nil|true|false)\b</string>
			<key>name</key>
			<string>constant.language.som</string>
		</dict>
		<key>eventualSendOperator</key>
		<dict>
			<key>match</key>
			<string>&lt;-:</string>
			<key>name</key>
			<string>keyword.operator.asyncsend.som</string>
		</dict>
		<key>exps</key>
		<dict>
			<key>name</key>
			<string>meta.expressions.som</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#parentheticalExp</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#multilinecomment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#blockExp</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#eventualSendOperator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numbers</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#returnOp</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#selfSuperOuter</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#assignmentOperator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#symbol</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#binarySelector</string>
				</dict>
			</array>
		</dict>
		<key>keyword</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.som</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(\w+:)</string>
		</dict>
		<key>keywordMsgPattern</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#slotDecl</string>
				</dict>
			</array>
		</dict>
		<key>keywordSegment</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.som</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.language.som</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\b\w+:)\s*(\w+\b)</string>
		</dict>
		<key>messagePattern</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#unaryMsgPattern</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#binaryMsgPattern</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywordMsgPattern</string>
				</dict>
			</array>
		</dict>
		<key>methodDecl</key>
		<dict>
			<key>begin</key>
			<string>(?:(\w+)|([+\/\\*~&lt;&gt;=@%|&amp;?!,-]+)\s+(\w+)|(?:\s*(\w+:)\s*(\w+)))\s*(=)\s*(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.som</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.som</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.language.som</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.som</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>variable.language.som</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.define-function.som</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.block.begin.som</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.block.end.som</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.declaration.som</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#exps</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#slotDecls</string>
				</dict>
			</array>
		</dict>
		<key>module</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#classHeader</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#classDefBlock</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#multilinecomment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#classSideColon</string>
				</dict>
			</array>
		</dict>
		<key>multilinecomment</key>
		<dict>
			<key>begin</key>
			<string>\(\*</string>
			<key>contentName</key>
			<string>comment</string>
			<key>end</key>
			<string>\*\)</string>
			<key>name</key>
			<string>comment</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#multilinecomment</string>
					<key>name</key>
					<string>comment</string>
				</dict>
			</array>
		</dict>
		<key>numbers</key>
		<dict>
			<key>match</key>
			<string>\b(\d+(\.\d+)?)\b</string>
			<key>name</key>
			<string>constant.numeric.som</string>
		</dict>
		<key>parentheticalExp</key>
		<dict>
			<key>begin</key>
			<string>\((?=[^*])</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.block.begin.som</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.block.end.som</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#exps</string>
				</dict>
			</array>
		</dict>
		<key>returnOp</key>
		<dict>
			<key>match</key>
			<string>\^</string>
			<key>name</key>
			<string>keyword.control.som</string>
		</dict>
		<key>selfSuperOuter</key>
		<dict>
			<key>match</key>
			<string>\b(self|super|outer)\b</string>
			<key>name</key>
			<string>variable.language.som</string>
		</dict>
		<key>slotDecl</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.som</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(\w+)\b</string>
		</dict>
		<key>slotDecls</key>
		<dict>
			<key>begin</key>
			<string>\|</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.block.begin.som</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\|</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.block.end.som</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#slotDef</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#multilinecomment</string>
				</dict>
			</array>
		</dict>
		<key>slotDef</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#accessModifier</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.language.som</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(\w+)\b</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(=|::=)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.variables.som</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\.</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.terminator.som</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#exps</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single</string>
		</dict>
		<key>symbol</key>
		<dict>
			<key>match</key>
			<string>#\w+\b</string>
			<key>name</key>
			<string>constant.character.symbol</string>
		</dict>
		<key>unaryMsgPattern</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#unarySelector</string>
				</dict>
			</array>
		</dict>
		<key>unarySelector</key>
		<dict>
			<key>match</key>
			<string>\b(\w+)\b</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.som</string>
	<key>uuid</key>
	<string>3791d52d-e561-4fb3-bb65-9c6b84ea333d</string>
</dict>
</plist>
