<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>som</string>
	</array>
	<key>name</key>
	<string>SOMns</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#multilinecomment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#compilationUnit</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(nil|true|false)\b</string>
			<key>name</key>
			<string>constant.language</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(self|super|outer)\b</string>
			<key>name</key>
			<string>variable.language</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(\d+(\.\d+)?)\b</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b#\w+</string>
			<key>name</key>
			<string>constant.character.symbol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>&lt;-:</string>
			<key>name</key>
			<string>keyword.operator.asyncsend</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>accessModifier</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.modifier.som</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(public|private|protected)\b</string>
		</dict>
		<key>binaryMsgPattern</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#binarySelector</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#slotDecl</string>
				</dict>
			</array>
		</dict>
		<key>classBody</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.block.begin.som</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=\))</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.block.end.som</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.definition.class.body.som</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#instanceInitializer</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sideDecl</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#classSideDecl</string>
				</dict>
			</array>
		</dict>
		<key>classCategory</key>
		<dict>
			<key>name</key>
			<string>classCategory</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
			</array>
		</dict>
		<key>classDecl</key>
		<dict>
			<key>begin</key>
			<string>(?=\w?[\w\s]*(?:class)\s+\w+\s*)</string>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.class.end.som</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.class.som</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#accessModifier</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.som</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.class.som</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(class)\s+(\w+)</string>
					<key>name</key>
					<string>meta.class.identifier.som</string>
				</dict>
				<dict>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.som</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.language.som</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?==)</string>
					<key>match</key>
					<string>\b(\w+(?::)?)\s+(\w+)</string>
					<key>name</key>
					<string>meta.messagePattern</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>=</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.extends.som</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\()</string>
					<key>name</key>
					<string>meta.definition.class.inherited.classes.som</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\b(\w+(?::)?)</string>
							<key>name</key>
							<string>entity.name.function.som</string>
						</dict>
						<dict>
							<key>match</key>
							<string>&lt;:</string>
							<key>name</key>
							<string>storage.modifier.mixin.som</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#classBody</string>
				</dict>
			</array>
		</dict>
		<key>colon</key>
		<dict>
			<key>match</key>
			<string>:</string>
			<key>name</key>
			<string>colon</string>
		</dict>
		<key>comma</key>
		<dict>
			<key>match</key>
			<string>,</string>
			<key>name</key>
			<string>comma</string>
		</dict>
		<key>compilationUnit</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#classCategory</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#classDecl</string>
				</dict>
			</array>
		</dict>
		<key>dot</key>
		<dict>
			<key>match</key>
			<string>\.</string>
			<key>name</key>
			<string>dot</string>
		</dict>
		<key>equalSign</key>
		<dict>
			<key>match</key>
			<string>=</string>
			<key>name</key>
			<string>equalSign</string>
		</dict>
		<key>eventualSendOperator</key>
		<dict>
			<key>match</key>
			<string>&lt;-:</string>
			<key>name</key>
			<string>keyword.operator.asyncsend</string>
		</dict>
		<key>id</key>
		<dict>
			<key>name</key>
			<string></string>
		</dict>
		<key>instanceInitializer</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#multilinecomment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#slotDecls</string>
				</dict>
			</array>
		</dict>
		<key>keyword</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.som</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(\w+:)</string>
		</dict>
		<key>keywordMsgPattern</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#slotDecl</string>
				</dict>
			</array>
		</dict>
		<key>messagePattern</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#unaryMsgPattern</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#binaryMsgPattern</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywordMsgPattern</string>
				</dict>
			</array>
		</dict>
		<key>multilinecomment</key>
		<dict>
			<key>begin</key>
			<string>\(\*</string>
			<key>contentName</key>
			<string>comment</string>
			<key>end</key>
			<string>\*\)</string>
			<key>name</key>
			<string>comment</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#multilinecomment</string>
					<key>name</key>
					<string>comment</string>
				</dict>
			</array>
		</dict>
		<key>slotDecl</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.som</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(\w+)\b</string>
		</dict>
		<key>slotDecls</key>
		<dict>
			<key>begin</key>
			<string>\|</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.block.begin.som</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\|</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.block.end.som</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#slotDef</string>
				</dict>
			</array>
		</dict>
		<key>slotDef</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.modifier.som</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.language.som</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(public|private|protected)\b\s+(\w+)\b</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(=|::=)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.variables.som</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\.</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.terminator.som</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single</string>
		</dict>
		<key>unaryMsgPattern</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#unarySelector</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.som</string>
	<key>uuid</key>
	<string>3791d52d-e561-4fb3-bb65-9c6b84ea333d</string>
</dict>
</plist>
